name: Docker Image CI

on:
  workflow_dispatch:

  push:
    branches: master

  schedule:
    - cron: "0 2 1 * *"

jobs:
  build:
    name: Deploy to GHCR
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Log in to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ekisu/docker-nginx-reverseproxy-letsencrypt:latest
          ekisu/docker-nginx-reverseproxy-letsencrypt:${{ steps.date.outputs.date }}
